# Generated by Django 3.2.19 on 2023-06-05 15:21

from django.db import migrations

GROUPS_TO_CREATE = ["Client", "Vendor"]


def forwards_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create(
        [Group(name=group) for group in GROUPS_TO_CREATE]
    )


def reverse_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name__in=GROUPS_TO_CREATE).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
