# Generated by Django 4.2.7 on 2023-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="uploads/", verbose_name="image"
            ),
        ),
    ]
